# Generated by Django 4.0 on 2023-05-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baidu_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='股票名称')),
                ('state', models.FloatField(blank=True, null=True, verbose_name='涨跌幅')),
                ('industry', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属板块')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='股票代码')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='现价')),
                ('abbr', models.CharField(blank=True, max_length=8, null=True, verbose_name='市场缩写')),
            ],
            options={
                'db_table': 'baidu_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='baidu_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='股票代码')),
                ('period', models.CharField(blank=True, max_length=8, null=True, verbose_name='周期')),
                ('bullish', models.IntegerField(blank=True, null=True, verbose_name='看涨')),
                ('bearish', models.IntegerField(blank=True, null=True, verbose_name='看跌')),
            ],
            options={
                'db_table': 'baidu_vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='em_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='股票代码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='股票名称')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='最新价')),
                ('state', models.FloatField(blank=True, null=True, verbose_name='涨跌幅')),
            ],
            options={
                'db_table': 'em_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rank_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='股票代码')),
                ('new_fans', models.FloatField(blank=True, null=True, verbose_name='新晋粉丝')),
                ('loyal_fans', models.FloatField(blank=True, null=True, verbose_name='铁杆粉丝')),
            ],
            options={
                'db_table': 'rank_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stock_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='股票代码')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('highest', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('lowest', models.FloatField(blank=True, null=True, verbose_name='最低价')),
            ],
            options={
                'db_table': 'stock_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stock_list',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='股票名称')),
                ('area', models.CharField(blank=True, max_length=32, null=True, verbose_name='地区')),
                ('industry', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属板块')),
                ('abbr', models.CharField(blank=True, max_length=8, null=True, verbose_name='市场缩写')),
            ],
            options={
                'db_table': 'stock_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stock_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='股票代码')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='新闻标题')),
                ('source', models.CharField(blank=True, max_length=32, null=True, verbose_name='文章来源')),
                ('link', models.URLField(blank=True, null=True, verbose_name='新闻链接')),
            ],
            options={
                'db_table': 'stock_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stock_spot',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='股票名称')),
                ('latest_price', models.FloatField(blank=True, null=True, verbose_name='最新价')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='涨跌幅')),
                ('change_amount', models.FloatField(blank=True, null=True, verbose_name='涨跌额')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='成交量')),
                ('turnover', models.FloatField(blank=True, null=True, verbose_name='成交额')),
                ('amplitude', models.FloatField(blank=True, null=True, verbose_name='振幅')),
                ('highest', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('lowest', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('today_open', models.FloatField(blank=True, null=True, verbose_name='今开')),
                ('prev_close', models.FloatField(blank=True, null=True, verbose_name='昨收')),
                ('volume_ratio', models.FloatField(blank=True, null=True, verbose_name='量比')),
                ('turnover_ratio', models.FloatField(blank=True, null=True, verbose_name='换手率')),
                ('price_earnings', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('price_book', models.FloatField(blank=True, null=True, verbose_name='市净率')),
                ('total_value', models.FloatField(blank=True, null=True, verbose_name='总市值')),
                ('circulation_value', models.FloatField(blank=True, null=True, verbose_name='流通市值')),
            ],
            options={
                'db_table': 'stock_spot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='weibo_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='股票名称')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='指数')),
            ],
            options={
                'db_table': 'weibo_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='xq_tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='股票代码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='股票名称')),
                ('follow', models.IntegerField(blank=True, null=True, verbose_name='关注')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='最新价')),
            ],
            options={
                'db_table': 'xq_tweet',
                'managed': False,
            },
        ),
    ]
